# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vaidya-healthcare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run:  npm install
    - run:  npm test
    
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://vaidyahealthcare.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_da010f4a12194f28bdfe206808f17c8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a29fb8b5b8bb494e8221279f8627ea94 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vaidyahealthcare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_da010f4a12194f28bdfe206808f17c8e }}/vaidya-healthcare:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vaidya-healthcare'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a235869c0524e1893fb21d4abc22617 }}
        images: 'vaidyahealthcare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_da010f4a12194f28bdfe206808f17c8e }}/vaidya-healthcare:${{ github.sha }}'
